export const EVENTS_CLEAR = 'EVENTS_CLEAR';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EVENTS_FILTER = 'EVENTS_FILTER';
export const EVENTS_ADD = 'EVENTS_ADD';
export const EVENTS_INPUT_NEW_EVENT = 'EVENTS_INPUT_NEW_EVENT';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';
export const GET_DATA_STARTED = 'GET_DATA_STARTED';
export const DETAILS_GET_START = 'DETAILS_GET_START';
export const DETAILS_GET_FAILED = 'DETAILS_GET_FAILED';
export const DETAILS_GET_SUCCESS = 'DETAILS_GET_SUCCESS';

export const DETAILS_SHOW = 'DETAILS_SHOW';